[project]
name = "fifantasy-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amplpy>=0.16.0",
    "duckdb>=1.4.4",
    "streamlit>=1.54.0",
]
